import React from 'react'
import Footer from '../components/Footer';
import { Link } from 'react-router-dom';

const Terms = () => {
  return (
    <>
      <section style={{marginBottom: '50px'}} className="title_2">
        <div className="container">
          <div className="row">
            <div className="col-12">
              <h1>Howlyr Terms of Use</h1>

              <p style={{ fontSize: '14px', color: 'white', opacity: 0.7}}> Effective Date: November 5, 2018</p>
              <br />
              <div className="row justify-content-center">
                <ul className="legal-nav">
                  <li> <Link className="nav-link" to="/">Home</Link> </li>
                  <li> <Link className="nav-link" to="/about">About Howlyr</Link> </li>
                  <li> <Link className="nav-link" to="/community">Community Guidelines</Link> </li>
                  <li> <Link className="nav-link" to="/terms-of-use">Terms of Use</Link> </li>
                  <li> <Link className="nav-link" to="/privacy-policy">Privacy Policy</Link> </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="legal">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-9">
              <p>This terms of use agreement (“Terms of Use”) is a binding contract between you, an individual user (referred to herein as “you” and “your”) and Howlyr, Inc. (referred to herein as “Howlyr,” “we,” “our” and “us”).  By accessing or using the Howlyr website(s), brand(s), product(s), service(s), application(s) (including mobile application(s)) and/or any other service(s) owned, operated, branded, and/or made available by Howlyr, Inc. (together, the “Service”), however accessed, you agree to be bound by these Terms of Use.  These Terms of Use affect your legal rights and obligations and, because privacy is important to us, our data and privacy policy (the “Privacy Policy”) is incorporated herein by reference (and can also be found <span> <Link to="/privacy-policy"> here</Link></span>).  If you do not agree to be bound by all of these Terms of Use, do not access and/or use the Service.</p>
              <p>
                There may be times when we offer a special feature that has its own terms and conditions that apply in addition to these Terms of Use. In those cases, the terms specific to the special feature control to the extent there is a conflict with these Terms of Use.
              </p>
              <p> <span>ARBITRATION NOTICE: EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE ARBITRATION SECTION BELOW, YOU AGREE THAT DISPUTES BETWEEN YOU AND HOWLYR WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT AND/OR CLASS-WIDE ARBITRATION.</span> </p>
              <h2>A.  Basic Terms</h2>
              <ol>
                <li> <p>You must be at least 13 years old to use the Service.  If you are at least 13 years old but under the age of 18, you must have been authorized to use the Service by your parent or legal guardian who is at least 18 years of age.  Therefore, by using the Service, you affirm that you are either (a) at least 18 years of age or (b) if not at least 18 years of age, then at least 13 years of age and have been authorized to use the Service by your parent or legal guardian who is at least 18 years of age.</p> </li>
                <li><p>You may not create, post and/or share violent, nude, partially nude, discriminatory, unlawful, infringing, hateful, pornographic or sexually suggestive photos, videos, and/or other content via the Service, and you may not create, post and/or share any content, in any form, which promotes any of the foregoing (i.e., violence, nudity, or material which is discriminatory, unlawful, infringing, hateful, pornographic or sexually suggestive) and/or violates or circumvents the spirit of these Terms of Use.  </p></li>
                <li><p>You are responsible for any activity that occurs through your account and you agree you will not sell, transfer, license or assign your account, followers (if any), username, or any account rights. With the exception of people or businesses that are expressly authorized to create accounts on behalf of their employers or clients, Howlyr prohibits the creation of and you agree that you will not create an account for anyone other than yourself. You also represent that all information you provide or provided to Howlyr upon registration and at all other times will be true, accurate, current and complete and you agree to update your information as necessary to maintain its truth and accuracy.</p> </li>
                <li><p>You agree that you will not solicit, collect or use the login credentials of other Howlyr users.</p> </li>
                <li> <p>You are responsible for keeping your password secret and secure. </p></li>
                <li> <p>You must not defame, stalk, bully, abuse, harass, threaten, impersonate or intimidate people or entities and you must not post private or confidential information via the Service, including, without limitation, your or any third party’s credit card information, social security number, driver’s license, passport number, or alternate national identity numbers, non-public phone numbers or non-public email addresses. </p></li>
                <li><p>You may not use the Service for any illegal or unauthorized purpose. You agree to comply with all laws, rules and regulations (for example, federal, state, local and provincial) applicable to your use of the Service and your Content (defined below), including but not limited to, copyright laws. </p>  </li>
                <li>
                  <p>You are solely responsible for your conduct and any data, text, files, information, usernames, images, graphics, photos, profiles, applications, links and other content or materials that you create, submit, post, and/or or display on and/or via the Service (collectively, "Content").</p></li>
                <li> <p>You must not change, modify, adapt or alter the Service or change, modify or alter another website, application and/or service so as to falsely imply that it is associated with the Service or Howlyr.</p></li>
                <li> <p>You must not access Howlyr's private API (if applicable) by means other than those permitted by Howlyr. Use of Howlyr's API (if and when applicable) will be subject to a separate set of terms ("API Terms").</p></li>
                <li><p>Howlyr is intended for personal, creative, and communicative purposes only. Neither Howlyr nor any of its Content may be used for commercial purposes.</p></li>
                <li><p>You must not create or submit unwanted email, comments, likes, favorites, or other forms of commercial or harassing communications (a/k/a "spam") to any Howlyr users and you will not pose unauthorized commercial communications (including spam) on and/or via the Service.  In addition to the foregoing, you must not (a) solicit, or attempt to solicit, personal information from other users of the Service, (b) create a false identity or impersonate another person or entity in any way, (c) create a new account on or through the Service, without Howlyr’s express written consent, if Howlyr has previously disabled or terminated your account, (d) disclose personal information about a third person on or through the Service, or obtained from the Service, without that person’s consent, (e) collect information about other users of the Service, (f) gain unauthorized access to the Service, to any other user’s account, name, or personally identifiable information, or to other computers, websites, or applications linked to the Service, (g) post any virus, worm, spyware, or any other code, file, or program that may or is intended to disable, overburden, impair, damage, or hijack the operation of any hardware, software, or telecommunications equipment, or any other aspect of the Service or communications equipment, computers, servers, and/or networks connected to the Service, (h) interfere with and/or disrupt the Service, networks, and/or servers connected to the Service and/or violate the regulations, policies, and/or procedures of those networks and/or servers, (i) violate any applicable federal, state, and/or local laws and/or regulations and/or the terms of these Terms of Use, and/or (j) assist or permit any person(s) or entity(ies) in engaging in any of the foregoing.</p></li>
                <li><p>You must not use domain names or web URLs in your username without prior written consent from Howlyr.</p></li>
                <li><p>You must not interfere or disrupt the Service or servers or networks connected to and/or in any way associated with the Service, including (but not limited to) by transmitting any worms, viruses, spyware, malware or any other code of a destructive or disruptive nature. You may not inject content or code or otherwise alter or interfere with the way any Howlyr page is rendered or displayed in a user's browser or device.</p></li>
                <li><p>You must comply with Howlyr's Community Guidelines, which can be found <span> <Link to="/community"> here</Link></span>. </p></li>
                <li><p>You must not create accounts with the Service through unauthorized means, including but not limited to, by using an automated device, script, bot, spider, crawler or scraper.</p></li>
                <li><p>You must not attempt to restrict another user from using or enjoying the Service and you must not encourage or facilitate violations of these Terms of Use or any other Howlyr terms.</p></li>
                <li><p>Violation of these Terms of Use may, in Howlyr's sole discretion, result in termination of your Howlyr account. You understand and agree that Howlyr cannot and will not be responsible for the Content posted on and/or via the Service and you use the Service at your own risk. If you violate the letter or spirit of these Terms of Use, or otherwise create risk or possible legal exposure for Howlyr, we can stop providing all or part of the Service to you.</p></li>
                <li> <p>The use of the Service may subject you to separate third party terms of service and/or fees, including, without limitation, your mobile network operator’s terms of service and fees, including, without limitation, fees charged for data usage and overage, which are your sole responsibility.</p></li>
                <li><p>You consent to the collection, use, and disclosure of your personally identifiable information by accessing and/or using the Service (including without limitation location information and personal data) in accordance with the terms of our <span> <Link to="/privacy-policy"> Privacy Policy</Link></span>.</p></li>
                <li><p>You are responsible for the security of your account, and are fully responsible for all activities that occur through the use of your credentials. Howlyr will not be liable for any loss or damage arising from unauthorized use of your credentials or loss of your credentials.</p></li>
              </ol>
              <h2>B.  General Conditions</h2>
              <ol>
                <li> <p>We reserve the right to modify or terminate the Service or your access to the Service for any reason, without notice, at any time, and without liability to you. You can deactivate your Howlyr account by contacting us at <span><a href="mailto:support@howlyr.com"> support@howlyr.com</a></span> with the subject line “Deactivate Account” and as further set forth in the Privacy Policy.  If we terminate your access to the Service or you deactivate your account, your photos, comments, likes, favorites, friendships, and all other data (if any) will no longer be accessible through your account (e.g., users will not be able to navigate to your username and view your photos, videos, soundbites, etc.).  Notwithstanding anything to the contrary contained in this Paragraph B(1), the foregoing materials, information, and data may persist and appear within the Service (e.g., if your Content has been reshared by others), on other social media websites and/or applications where such Content has been shared by you and/or reshared by others, and/or on mobile devices and other devices where such Content has been shared by you and/or reshared by others.
                </p></li>
                <li><p>Upon termination, all licenses and other rights granted to you in these Terms of Use (if any) will immediately cease.
                </p></li>
                <li><p>We reserve the right, in our sole discretion, to change these Terms of Use ("Updated Terms") from time to time. Unless we make a change for legal or administrative reasons, we will provide reasonable advance notice before the Updated Terms become effective. You agree that we may notify you of the Updated Terms by posting them on the Service, and that your use of the Service after the effective date of the Updated Terms (or engaging in such other conduct as we may reasonably specify) constitutes your agreement to the Updated Terms. Therefore, you should review these Terms of Use and any Updated Terms before using the Service. The Updated Terms will be effective as of the time of posting, or such later date as may be specified in the Updated Terms, and will apply to your use of the Service from that point forward. These Terms of Use will govern any disputes arising before the effective date of the Updated Terms.  If any Updated Terms are not acceptable to you, then your sole remedy is to stop accessing and using the Service.
  </p></li><li><p>We reserve the right to refuse access to the Service to anyone for any reason at any time.
  </p></li><li><p>We reserve the right to force forfeiture of any username for any reason.
  </p></li><li><p>We may, but have no obligation to, remove, edit, block, and/or monitor Content and/or accounts containing Content that we determine in our sole discretion violates these Terms of Use.
  </p></li><li><p>You are solely responsible for your interaction with other users of the Service, whether online or offline. You agree that Howlyr is not responsible or liable for the conduct of any user. Howlyr reserves the right, but has no obligation, to monitor or become involved in disputes between you and other users. Exercise common sense and your best judgment when interacting with others, including when you create, submit, post and/or share Content or any personal or other information.
  </p></li><li><p>There may be links from the Service, or from communications you receive from the Service, to third-party websites, applications and/or features. There may also be links to third-party websites, applications and/or features in images or comments within the Service and/or files derived from the Service. The Service also includes third-party content that we do not control, maintain or endorse. Functionality on the Service may also permit interactions between the Service and a third-party website(s), application(s) and/or feature(s), including (but not limited to) applications that connect the Service or your profile on the Service with a third-party website(s), application(s) and/or feature(s). For example, the Service may include a feature that enables you to share Content from the Service or your Content with a third party, which may be publicly posted on that third party's service or application. Using this functionality typically requires you to login to your account on the third-party service and you do so at your own risk. Howlyr does not control any of these third-party services or any of their content. You expressly acknowledge and agree that Howlyr is in no way responsible or liable for any such third-party services, websites, applications and/or features. YOUR CORRESPONDENCE AND BUSINESS DEALINGS WITH THIRD PARTIES FOUND THROUGH THE SERVICE ARE SOLELY BETWEEN YOU AND THE THIRD PARTY. You may choose, at your sole and absolute discretion and risk, to use applications that connect the Service or your profile on the Service with a third-party website(s), application(s), feature(s) and/or service(s) (each, an "Application") and such Application may interact with, connect to or gather and/or pull information from and to your Service profile. By using such Applications, you acknowledge and agree to the following: (a) if you use an Application to share information, you are consenting to information about your profile on the Service being shared; (b) your use of an Application may cause personally identifying information to be publicly disclosed and/or associated with you, even if Howlyr has not itself provided such information; and (c) your use of an Application is at your own option and risk, and may subject you to the terms of use of such Application, and you will hold the Howlyr Parties (defined below) harmless for activity related to the Application.
  </p></li><li><p>You agree that you are responsible for all data charges you incur through use of the Service.
  </p></li><li><p>We prohibit crawling, scraping, caching or otherwise accessing any content on the Service via automated means, including but not limited to, data, backend files, and user profiles and photos (except as may be the result of standard search engine protocols or technologies used by a search engine with Howlyr's express consent).
        </p></li><li><p>Howlyr provides the Service for free to you for your personal enjoyment and self-expression.  In return for enjoying such free access and use of the Service, you acknowledge and agree that Howlyr may generate revenues, increase goodwill and/or otherwise increase the value of Howlyr from your use of the Service, including, by way of example and not limitation, through the sale of advertising, sponsorships, promotions, and usage data, and you will have no right to share in any such revenue, goodwill and/or value whatsoever.  You further acknowledge that you have no right to receive any income or other consideration from (a) any Content that you create and/or (b) your use of any musical works, sound recordings, and/or other clips and/or files that you create (or use to create Content) and/or are made available to you on or through the Service (the “Underlying Content”), and you are prohibited from exercising any rights to monetize or obtain consideration from any Content or Underlying Content. </p></li></ol>
              <h2> C.  Rights </h2>
              <ol>
                <li><p>Howlyr does not claim ownership of any Content that you create or post on or through the Service. Instead, to the extent that any rights in and to the Content is deemed to vest in you, you hereby grant to Howlyr an exclusive, fully paid and royalty-free, transferable, sub-licensable, worldwide license, in perpetuity, to use (and otherwise make available to other users) the Content that you create and/or post on or through the Service, and any data and/or information in connection with your use of the Service for any purpose (including without limitation advertising, marketing, and promoting Howlyr and/or the Service, displaying and sharing your Content to other users of the Service, and otherwise providing the Service), subject to the Service's Privacy Policy.  Subject to the Service’s Privacy Policy, you also grant Howlyr a non-exclusive, fully paid and royalty-free, transferable, sub-licensable, worldwide license, in perpetuity, to use your name, image, voice, and likeness for any purpose, and that any Content posted by you to or through the Service will be considered non-confidential and non-propriety to you, and treated as such by Howlyr, and may be used by Howlyr in accordance with these Terms of Use without notice to you and without any liability to Howlyr.  For the avoidance of doubt, the rights granted in this paragraph include, but are not limited to, the right to reproduce sound recordings (and make mechanical reproductions of the musical works embodied in such sound recordings), and publicly perform and communicate to the public sound recordings (and the musical works embodied therein), all on a royalty-free basis (i.e., without the obligation to pay royalties to any third party, including but not limited to a sound recording copyright owner (e.g., a record label), a musical work copyright owner (e.g., a music publisher), a performing rights organization (e.g., ASCAP, BMI, SESAC, etc.), a sound recording PRO (e.g., SoundExchange), any unions and/or guilds, and/or any engineers, producers, and/or other royalty participants involved in the creation of the Content and/or Underlying Content.  Howlyr is under no obligation to delete any Content that you submit to the Service and/or post via the Service (including but not limited to any audio clips that you create).  NO RIGHTS ARE LICENSED BY HOWLYR TO YOU WITH RESPECT TO UNDERLYING CONTENT (WHETHER CREATED BY YOU OR MADE AVAILABLE FROM ANY HOWLYR-PROVIDED LIBRARY OR DATABASE OF CONTENT).  YOU USE ALL SUCH CONTENT AT YOUR SOLE RISK EVEN THOUGH SUCH CONTENT MAY BE MADE AVAILABLE TO YOU THROUGH THE SERVICE.</p>
                </li><li><p>Some of the Service may be supported by advertising revenue and may display advertisements and promotions, and you hereby agree that Howlyr may place such advertising and promotions on the Service or on, about, or in conjunction with your Content. The manner, mode and extent of such advertising and promotions are subject to change without specific notice to you.</p>
                </li><li><p>You acknowledge that we may not always identify paid services, sponsored content, or commercial communications as such.</p>
                </li><li><p>You represent and warrant that: (a) subject to any third party rights (if any) in any pre-existing Underlying Content included within your Content, you own the Content posted by you on or through the Service (subject to your license of such Content to Howlyr set forth above) or otherwise have the right to grant the rights and licenses set forth in these Terms of Use (provided, however, that the parties acknowledge that any Underlying Content accessed, used, and/or created by you will not be considered a separate copyrightable work and all rights (if any) in all such Underlying Content may remain with the owners of such Underlying Content); (b) the posting and use of your Content on or through the Service does not violate, misappropriate or infringe on the rights of any third party, including, without limitation, privacy rights, publicity rights, copyrights, trademark and/or other intellectual property rights; (c) you agree to pay for all royalties, fees, and any other monies owed by reason of Content and/or Underlying Content you post on or through the Service; and (d) you have the legal right and capacity to enter into these Terms of Use in your jurisdiction.</p>
                </li><li><p>The Service contains content owned or licensed by Howlyr or its third party licensors ("Howlyr Content"). Howlyr Content is protected by copyright, trademark, patent, trade secret and other laws, and, as between you and Howlyr, Howlyr owns and retains all rights (including but not limited to all design rights, databases, compilations and other intellectual property rights) in and to the Howlyr Content and the Service, in each case whether registered or unregistered, and any related goodwill. You will not remove, alter or conceal any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Howlyr Content and you will not reproduce, modify, adapt, prepare derivative works based on, perform, display, publish, distribute, transmit, broadcast, sell, license or otherwise exploit the Howlyr Content.</p>
                </li><li><p>The Howlyr name, logo(s), and service marks are trademarks of Howlyr, and may not be copied, imitated or used, in whole or in part, without the prior written permission of Howlyr. In addition, all page headers, custom graphics, button icons and scripts are copyrights, service marks, trademarks and/or trade dress of Howlyr, and may not be copied, imitated, or used in any way, in whole or in part, without prior written permission from Howlyr.</p>
                </li><li><p>Although it is Howlyr's intention for the Service to be available as much as possible, there will be occasions when the Service may be interrupted, including, without limitation, for scheduled maintenance or upgrades, for emergency repairs, or due to failure of telecommunications links and/or equipment. Also, Howlyr reserves the right to remove any Content from the Service for any reason, without prior notice. Content removed from the Service may continue to be stored by Howlyr, including, without limitation, in order to comply with certain legal obligations, but may not be retrievable without a valid court order. Consequently, Howlyr encourages you to maintain your own backup of your Content. In other words, Howlyr is not a backup service and you agree that you will not rely on the Service for the purposes of Content backup or storage. Howlyr will not be liable to you for any modification, suspension, or discontinuation of the Services, or the loss of any Content. You also acknowledge that the Internet may be subject to breaches of security and that the submission of Content or other information may not be secure.</p>
                </li><li><p>You agree that Howlyr is not responsible for, and does not endorse, Content posted within the Service. Howlyr does not have any obligation to prescreen, monitor, edit, or remove any Content or Underlying Content. Howlyr reserves the right to remove, disallow, block, and/or delete any Content and/or Underlying Content, whether or not made available by Howlyr or created by you or any other user. If your Content violates these Terms of Use, you may bear legal responsibility for that Content.</p>
                </li><li><p>Except as otherwise described in the Service's Privacy Policy, as between you and Howlyr, any Content will be non-confidential and non-proprietary and we will not be liable for any use or disclosure of Content. You acknowledge and agree that your relationship with Howlyr is not a confidential, fiduciary, or other type of special relationship, and that your decision to submit any Content does not place Howlyr in a position that is any different from the position held by members of the general public, including with regard to your Content. None of your Content will be subject to any obligation of confidence on the part of Howlyr, and Howlyr will not be liable for any use or disclosure of any Content you provide.</p>
                </li><li><p>It is Howlyr's policy not to accept or consider content, information, ideas, suggestions or other materials other than those we have specifically requested and to which certain specific terms, conditions and requirements may apply. This is to avoid any misunderstandings if your ideas are similar to those we have developed or are developing independently. Accordingly, Howlyr does not accept unsolicited materials or ideas, and takes no responsibility for any materials or ideas so transmitted. If, despite our policy, you choose to send us content, information, ideas, suggestions, or other materials, you further agree that Howlyr is free to use any such content, information, ideas, suggestions or other materials, for any purposes whatsoever, including, without limitation, developing and marketing products and services, without any liability or payment of any kind to you.</p>
                </li><li><p>By creating and/or sharing Content to or through the Service, you waive any rights to prior inspection or approval of any marketing or promotional materials related to such Content. You also waive any and all rights of privacy, publicity, or any other rights of a similar nature in connection with your Content, or any portion thereof. To the extent any moral rights are not transferable or assignable, you hereby waive and agree never to assert any and all moral rights, or to support, maintain or permit any action based on any moral rights that you may have in or with respect to any Content you create and/or share to or through the Service.</p>
                </li><li><p>The Service contains certain open source software.  Each item of open source software is subject to its own applicable license terms, which can be found below.</p> </li>
              </ol>
              <h2>D. Open Source Software Notices</h2>
              <p>The Service does or may contain the following open source software: </p>
              <ol>
                <li> <p><span>PryntTrimmerView. </span> This software is governed by the following license:</p>
                  <p>MIT License </p>
                  <p>Copyright (c) 2017 Prynt </p>
                  <p>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions: </p>
                  <p>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. </p>
                  <p>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. </p>
                  <p>  See: https://github.com/HHK1/PryntTrimmerView for details </p></li>
                <li> <p>	<span> PhoneNumberKit. </span> This software is governed by the following license: </p>
                  <p>The MIT License (MIT) </p>
                  <p>Copyright (c) 2015 Roy Marmelstein </p>
                  <p>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions: </p>
                  <p>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. </p>
                  <p>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. </p>
                  <p>See: https://github.com/marmelroy/PhoneNumberKit for details </p> </li>
                <li><p><span> SwiftKeychainWrapper. </span> This software is governed by the following license:</p>
                  <p>The MIT License (MIT)</p>
                  <p>Copyright (c) 2014 Jason Rendel </p>
                  <p>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions: </p>
                  <p>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.</p>
                  <p>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.</p>
                  <p>See: https://github.com/jrendel/SwiftKeychainWrapper for details </p> </li>
                <li><p> <span>JSONWebToken.swift.</span>  This software is governed by the following license:</p>
                  <p>Copyright (c) 2015, Kyle Fuller </p>
                  <p>All rights reserved. </p>
                  <p>Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:</p>
                  <p>* Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. </p>

                  <p>* Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. </p>

                  <p>THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. </p>

                  <p>See: https://github.com/kylef/JSONWebToken.swift for details </p></li>

                <li> <p> <span>RecordButton. </span> This software is governed by the following license:</p>
                  <p>The MIT License (MIT)</p>

                  <p>Permission is hereby granted, free of charge, to any person obtaining a copy
                  of this software and associated documentation files (the "Software"), to deal
                  in the Software without restriction, including without limitation the rights
                  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
                  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions: </p>

                  <p>The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software. </p>

                  <p>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
                  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
                  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
                  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
                  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
                  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE. </p>

                  <p>See: https://github.com/samuelbeek/RecordButton for details.</p>
                </li>

              </ol>





              <h2>E. DMCA Copyright Policy: Reporting Copyright and Other IP Violations</h2>


              <ol>
                <li><p>We respect other people's rights, and expect you to do the same. </p></li>
                <li><p>We provide you with tools to help you protect your intellectual property rights. If you believe that any Content or Underlying Content made available on or through the Service has been used or exploited in a manner that infringes an intellectual property right you own or control, then please promptly send a “Notification of Claimed Infringement” containing the following information to the Designated Agent identified below. Your Notification of Claimed Infringement may be shared by Howlyr with the user alleged to have infringed a right you own or control, and you hereby consent to Howlyr making such disclosure. Your communication must include substantially the following: </p>
                  <ul>
                    <li><p>A physical or electronic signature of a person authorized to act on behalf of the owner of the work(s) that has/have been allegedly infringed.  If you are an authorized representative of the owner, such as an attorney, please be sure to specify your relationship with the owner; </p></li>
                    <li><p>Identification of works or materials being infringed, or, if multiple works are covered by a single notification, then a representative list of such works;</p></li>
                    <li><p>Identification of the specific material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit Howlyr to locate the material;</p></li>
                    <li><p>Your contact information, including your full legal name (not that of a company), an email address, a physical address, and a phone number. If you are an authorized representative of the owner, such as an attorney, please be sure to specify your relationship to the owner; </p></li>
                    <li><p>A statement that you have a good faith belief that the use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</p></li>
                    <li><p>A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. You should consult with your own lawyer and/or see 17 U.S.C. § 512 to confirm your obligations to provide a valid notice of claimed infringement.</p></li> </ul>

                  <p>Designated Agent Contact Information. Howlyr's designated agent for receipt of Notifications of Claimed Infringement (the “Designated Agent”) can be contacted at: </p>
                  <p>
                    Via E-mail: howlyrinc@howlyr.com </p>
                  <p>
                    Via U.S. Mail: Howlyr, Inc., Attention: Copyright, Howlyr, Inc., 5023 North Parkway Calabasas, Calabasas, CA 91302
          </p> <p>
                    If you receive a notification from Howlyr that material made available by you on or through the Service has been the subject of a Notification of Claimed Infringement, then you will have the right to provide Howlyr with what is called a “Counter Notification.” To be effective, a Counter Notification must be in writing, provided to Howlyr’s Designated Agent and include substantially the following information: </p>
                  <ul>
                    <li><p>A physical or electronic signature of the user; </p></li>
                    <li><p>Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;</p></li>
                    <li><p>A statement under penalty of perjury that the user has a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled; </p></li>
                    <li><p>Your contact information, including your full legal name (not that of a company), an email address, a physical address, and a phone number.  If you are an authorized representative of the uploader, such as an attorney, please be sure to specify your relationship to the uploader; and</p></li>
                    <li><p>The user’s name, address, and telephone number, and a statement that the user consents to the jurisdiction required by Howlyr, or if the user’s address is outside of the United States, then for any judicial district in which Howlyr may be found, and that the user will accept service of process from the person who provided the Notification of Claimed Infringement as set forth above or an agent of such person.</p>

                      <p>A party submitting a Counter Notification should consult a lawyer or see 17 U.S.C. § 512 to confirm the party’s obligations to provide a valid counter notification under the Copyright Act.</p></li></ul>


                  <p>
                    If you submit a Counter Notification to Howlyr in response to a Notification of Claimed Infringement, then Howlyr will promptly provide the person who provided the Notification of Claimed Infringement with a copy of your Counter Notification and inform that person that Howlyr will replace or reinstate the removed material or cease disabling access to it in 10 business days, and Howlyr will replace or reinstate the removed material and cease disabling access to it following receipt of the Counter Notification, unless Howlyr’s Designated Agent receives notice from the party that submitted the Notification of Claimed Infringement that such person has filed an action seeking a court order to restrain the user from engaging in infringing activity relating to the material on the Howlyr’s system or network. </p>
                  <p>
                    The Copyright Act provides that:</p>
                  <p>
                    [a]ny person who knowingly materially misrepresents under [Section 512 of the Copyright Act (17 U.S.C. § 512)] (1) that material or activity is infringing, or (2) that material or activity was removed or disabled by mistake or misidentification, will be liable for any damages, including costs and attorneys’ fees, incurred by the alleged infringer, by any copyright owner or copyright owner’s authorized licensee, or by a service provider, who is injured by such misrepresentation, as the result of [Howlyr] relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing, or in replacing the removed material or ceasing to disable access to it. </p>


                  <p>17 U.S.C. § 512(f). </p>
                  <p>
                    Howlyr reserves the right to seek damages and/or all other forms of legal and/or equitable relief to the extent permitted by law from any party that submits a Notification of Claimed Infringement or Counter Notification in violation of the law.</p> </li>
                <li><p>If you repeatedly infringe other people's intellectual property rights, we will disable your account when appropriate.</p></li>



              </ol>



              <h2>F. Advertisements and Other Commercial Content</h2>
              <ol>
                <li><p>You give Howlyr permission to use your name, image, Content, voice, likeness, and/or other information in connection with commercial, sponsored, and/or related content (such as a brand you like) served or enhanced by Howlyr. This means, for example, that you permit a business or other entity to pay Howlyr to display your name and/or profile picture (if any) with your content or information, without any compensation to you. If you have selected a specific audience for your content or information, we will respect your choice when we use it. If you are under the age of eighteen (18), you represent that a parent or legal guardian also agrees to this section on your behalf. </p></li>
                <li><p>
                  You understand that Howlyr may not always identify paid services and communications as such.</p>
                </li>
              </ol>

              <h2>G. Disclaimer of Warranties</h2>

              <p>THE SERVICE, INCLUDING, WITHOUT LIMITATION, CONTENT, UNDERLYING CONTENT, AND HOWLYR CONTENT, IS PROVIDED ON AN "AS IS", "AS AVAILABLE" AND "WITH ALL FAULTS" BASIS. TO THE FULLEST EXTENT PERMISSIBLE BY LAW, NEITHER HOWLYR NOR ITS PARENT COMPANY (IF ANY) NOR ANY OF ITS AFFILIATES OR SUBSIDIARIES, NOR ANY OF THEIR EMPLOYEES, MANAGERS, DIRECTORS, OFFICERS OR AGENTS (COLLECTIVELY, THE "HOWLYR PARTIES") MAKE ANY REPRESENTATIONS OR WARRANTIES OR ENDORSEMENTS OF ANY KIND WHATSOEVER, EXPRESS OR IMPLIED, AS TO: (A) THE SERVICE; (B) THE CONTENT, UNDERLYING CONTENT, OR THE HOWLYR CONTENT; (C) USER CONTENT; OR (D) SECURITY ASSOCIATED WITH THE TRANSMISSION OF INFORMATION TO HOWLYR OR VIA THE SERVICE. IN ADDITION, THE HOWLYR PARTIES HEREBY DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, TITLE, CUSTOM, TRADE, QUIET ENJOYMENT, SYSTEM INTEGRATION AND FREEDOM FROM COMPUTER VIRUS. </p>
              <p>
                THE HOWLYR PARTIES DO NOT REPRESENT OR WARRANT THAT THE SERVICE WILL BE ERROR-FREE OR UNINTERRUPTED; THAT DEFECTS WILL BE CORRECTED; OR THAT THE SERVICE OR THE SERVER THAT MAKES THE SERVICE AVAILABLE IS FREE FROM ANY HARMFUL COMPONENTS, INCLUDING, WITHOUT LIMITATION, VIRUSES. THE HOWLYR PARTIES DO NOT MAKE ANY REPRESENTATIONS OR WARRANTIES THAT THE INFORMATION (INCLUDING ANY INSTRUCTIONS) ON THE SERVICE IS ACCURATE, COMPLETE, OR USEFUL. YOU ACKNOWLEDGE THAT YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK. THE HOWLYR PARTIES DO NOT WARRANT THAT YOUR USE OF THE SERVICE IS LAWFUL IN ANY PARTICULAR JURISDICTION, AND THE HOWLYR PARTIES SPECIFICALLY DISCLAIM SUCH WARRANTIES. SOME JURISDICTIONS LIMIT OR DO NOT ALLOW THE DISCLAIMER OF IMPLIED OR OTHER WARRANTIES SO THE ABOVE DISCLAIMER MAY NOT APPLY TO YOU TO THE EXTENT SUCH JURISDICTION'S LAW IS APPLICABLE TO YOU AND THESE TERMS OF USE. </p>
              <p>
                BY ACCESSING OR USING THE SERVICE YOU REPRESENT AND WARRANT THAT YOUR ACTIVITIES ARE LAWFUL IN EVERY JURISDICTION WHERE YOU ACCESS OR USE THE SERVICE. </p>
              <p>
                THE HOWLYR PARTIES DO NOT ENDORSE CONTENT AND/OR UNDERLYING CONTENT AND SPECIFICALLY DISCLAIM ANY RESPONSIBILITY OR LIABILITY TO ANY PERSON OR ENTITY FOR ANY LOSS, DAMAGE (WHETHER ACTUAL, CONSEQUENTIAL, PUNITIVE OR OTHERWISE), INJURY, CLAIM, LIABILITY OR OTHER CAUSE OF ANY KIND OR CHARACTER BASED UPON OR RESULTING FROM ANY CONTENT AND/OR UNDERLYING CONTENT.
  </p>

              <h2> H. Limitation of Liability; Waiver </h2>
              <p>UNDER NO CIRCUMSTANCES WILL THE HOWLYR PARTIES BE LIABLE TO YOU FOR ANY LOSS OR DAMAGES OF ANY KIND (INCLUDING, WITHOUT LIMITATION, FOR ANY DIRECT, INDIRECT, ECONOMIC, EXEMPLARY, SPECIAL, PUNITIVE, INCIDENTAL AND/OR CONSEQUENTIAL LOSSES AND/OR DAMAGES) INCLUDING BUT NOT LIMITED TO THOSE THAT ARE DIRECTLY OR INDIRECTLY RELATED TO: (1) THE SERVICE; (2) THE CONTENT, UNDERLYING CONTENT, OR THE HOWLYR CONTENT; (3) USER CONTENT; (4) YOUR USE OF, INABILITY TO USE, OR THE PERFORMANCE OF THE SERVICE; (5) ANY ACTION TAKEN IN CONNECTION WITH AN INVESTIGATION BY THE HOWLYR PARTIES OR LAW ENFORCEMENT AUTHORITIES REGARDING YOUR OR ANY OTHER PARTY'S USE OF THE SERVICE; (6) ANY ACTION TAKEN IN CONNECTION WITH COPYRIGHT AND/OR OTHER INTELLECTUAL PROPERTY MATTERS; (7) ANY ERRORS OR OMISSIONS IN THE SERVICE'S OPERATION; AND/OR (8) ANY DAMAGE TO ANY USER'S COMPUTER, MOBILE DEVICE, OR OTHER EQUIPMENT OR TECHNOLOGY INCLUDING, WITHOUT LIMITATION, DAMAGE FROM ANY SECURITY BREACH OR FROM ANY VIRUS, BUGS, TAMPERING, FRAUD, ERROR, OMISSION, INTERRUPTION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER LINE OR NETWORK FAILURE OR ANY OTHER TECHNICAL OR OTHER MALFUNCTION, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, LOSS OF DATA, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, EVEN IF FORESEEABLE OR EVEN IF THE HOWLYR PARTIES HAVE BEEN ADVISED OF OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE, STRICT LIABILITY OR TORT (INCLUDING, WITHOUT LIMITATION, WHETHER CAUSED IN WHOLE OR IN PART BY NEGLIGENCE, ACTS OF GOD, TELECOMMUNICATIONS FAILURE, OR THEFT OR DESTRUCTION OF THE SERVICE). IN NO EVENT WILL THE HOWLYR PARTIES BE LIABLE TO YOU OR ANYONE ELSE FOR LOSS, DAMAGE OR INJURY, INCLUDING, WITHOUT LIMITATION, DEATH OR PERSONAL INJURY. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. IN NO EVENT WILL THE HOWLYR PARTIES TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES OR CAUSES OR ACTION EXCEED ONE HUNDRED UNITED STATES DOLLARS ($100.00). </p>

              <p>

                YOU AGREE THAT IN THE EVENT YOU INCUR ANY DAMAGES, LOSSES OR INJURIES THAT ARISE OUT OF HOWLYR'S ACTS OR OMISSIONS, THE DAMAGES, IF ANY, CAUSED TO YOU ARE NOT IRREPARABLE OR SUFFICIENT TO ENTITLE YOU TO AN INJUNCTION PREVENTING ANY EXPLOITATION OF ANY WEB SITE, APPLICATION, SERVICE, PROPERTY, PRODUCT OR OTHER CONTENT OWNED OR CONTROLLED BY THE HOWLYR PARTIES, AND YOU WILL HAVE NO RIGHTS TO ENJOIN OR RESTRAIN THE DEVELOPMENT, PRODUCTION, DISTRIBUTION, ADVERTISING, EXHIBITION OR EXPLOITATION OF ANY WEBSITE, PROPERTY, PRODUCT, SERVICE, APPLICATION OR OTHER CONTENT OWNED, CONTROLLED OR BRANDED BY THE HOWLYR PARTIES. </p>
              <p>
                BY ACCESSING THE SERVICE, YOU UNDERSTAND THAT YOU MAY BE WAIVING RIGHTS WITH RESPECT TO CLAIMS THAT ARE AT THIS TIME UNKNOWN OR UNSUSPECTED, AND IN ACCORDANCE WITH SUCH WAIVER, YOU ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTAND, AND HEREBY EXPRESSLY WAIVE, THE BENEFITS OF SECTION 1542 OF THE CIVIL CODE OF CALIFORNIA, AND ANY SIMILAR LAW OF ANY STATE OR TERRITORY, WHICH PROVIDES AS FOLLOWS: "A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR." </p>
              <p>
                HOWLYR IS NOT RESPONSIBLE FOR THE ACTIONS, CONTENT, INFORMATION, OR DATA OF THIRD PARTIES, AND YOU RELEASE US, OUR DIRECTORS, OFFICERS, EMPLOYEES, AND AGENTS FROM ANY CLAIMS AND DAMAGES, KNOWN AND UNKNOWN, ARISING OUT OF OR IN ANY WAY CONNECTED WITH ANY CLAIM YOU HAVE AGAINST ANY SUCH THIRD PARTIES. </p>


              <h2>I.  Indemnification </h2>

              <p>
                You (and also any third party for whom you operate an account or activity on the Service) agree to defend (at Howlyr's request), indemnify and hold the Howlyr Parties harmless from and against any claims, liabilities, damages, losses, and expenses, including without limitation, reasonable attorney's fees and costs, arising out of or in any way connected with any of the following (including as a result of your direct activities on the Service or those conducted on your behalf): (i) your Content or your access to or use of the Service; (ii) your breach or alleged breach of these Terms of Use; (iii) your violation of any third-party right, including without limitation, any intellectual property right, publicity, confidentiality, property or privacy right; (iv) your violation of any laws, rules, regulations, codes, statutes, ordinances or orders of any governmental and quasi-governmental authorities, including, without limitation, all regulatory, administrative and legislative authorities; or (v) any misrepresentation made by you. You will cooperate as fully required by Howlyr in the defense of any claim. Howlyr reserves the right to assume the exclusive defense and control of any matter subject to indemnification by you, and you will not in any event settle any claim without the prior written consent of Howlyr. </p>

              <h2> J.  Arbitration </h2>

              <p>
                Except for disputes relating to the enforceability of the class action waiver set forth below and the enforceability of this Section J ("Excluded Disputes"), you agree that all disputes between you and Howlyr (whether or not such dispute involves a third party) with regard to your relationship with Howlyr, including without limitation disputes related to these Terms of Use, your use of the Service, and/or rights of privacy and/or publicity, will be resolved by binding, individual arbitration under JAMS's rules for arbitration of consumer-related disputes and you and Howlyr hereby expressly waive trial by jury. As an alternative, you may bring your claim in your local "small claims" court, if permitted by that small claims court's rules. You may bring claims only on your own behalf. Neither you nor Howlyr will participate in a class action or class-wide arbitration for any claims covered by this agreement. You also agree not to participate in claims brought in a private attorney general or representative capacity, or consolidated claims involving another person's account, if Howlyr is a party to the proceeding. This dispute resolution provision will be governed by the Federal Arbitration Act. In the event JAMS is unwilling or unable to set a hearing date within one hundred and sixty (160) days of filing the case, then either Howlyr or you can elect to have the arbitration administered instead by the American Arbitration Association. Judgment on the award rendered by the arbitrator may be entered in any court having competent jurisdiction. Any provision of applicable law notwithstanding, the arbitrator will not have authority to award damages, remedies or awards that conflict with these Terms of Use. </p>
              <p>
                This arbitration agreement will survive the termination of your relationship with Howlyr.  Notwithstanding anything to the contrary herein, Howlyr reserves the right to resolve any disputes (including, but not limited to, for preliminary or injunctive relief) in a court of competent jurisdiction (and any such disputes shall also be deemed Excluded Disputes for purposes of these Terms of Use). </p>


              <h2>    K.  Time Limitation on Claims </h2>
              <p>You agree that any claim you may have arising out of or related to your relationship with Howlyr must be filed within one year after such claim arose; otherwise, your claim is permanently barred. </p>
              <h2> L.  Governing Law & Venue </h2>
              <p>These Terms of Use are governed by and construed in accordance with the laws of the State of California, without giving effect to any principles of conflicts of law AND WILL SPECIFICALLY NOT BE GOVERNED BY THE UNITED NATIONS CONVENTIONS ON CONTRACTS FOR THE INTERNATIONAL SALE OF GOODS, IF OTHERWISE APPLICABLE. For any action at law or in equity relating to the arbitration provision of these Terms of Use or the Excluded Disputes, you agree to resolve any dispute you have with Howlyr exclusively in a state or federal court located in Los Angeles, California, and to submit to the personal jurisdiction of the courts located in Los Angeles County for the purpose of litigating all such disputes. </p>
              <p>
                If any provision of these Terms of Use is held to be unlawful, void, or for any reason unenforceable during arbitration or by a court of competent jurisdiction, then that provision will be deemed severable from these Terms of Use and will not affect the validity and enforceability of any remaining provisions. Howlyr's failure to insist upon or enforce strict performance of any provision of these Terms will not be construed as a waiver of any provision or right. No waiver of any of these Terms will be deemed a further or continuing waiver of such term or condition or any other term or condition. Howlyr reserves the right to change this dispute resolution provision, but any such changes will not apply to disputes arising before the effective date of the amendment. This dispute resolution provision will survive the termination of any or all of your transactions with Howlyr and/or use of the Service. </p>
              <h2>M.  Entire Agreement </h2>

              <p>
                If you are using the Service on behalf of a legal entity, you represent that you are authorized to enter into an agreement on behalf of that legal entity. These Terms of Use constitute the entire agreement between you and Howlyr and governs your use of the Service, superseding any prior agreements between you and Howlyr. You will not assign the Terms of Use or assign any rights or delegate any obligations hereunder, in whole or in part, whether voluntarily or by operation of law, without the prior written consent of Howlyr. Any purported assignment or delegation by you without the appropriate prior written consent of Howlyr will be null and void. Howlyr may assign these Terms of Use or any rights hereunder without your consent. If any provision of these Terms of Use is found by a court of competent jurisdiction to be invalid or otherwise unenforceable, the parties nevertheless agree that such portion will be deemed severable from these Terms of Use and will not affect the validity and enforceability of the remaining provisions, and the remaining provisions of the Terms of Use remain in full force and effect. Neither the course of conduct between the parties nor trade practice will act to modify the Terms of Use. These Terms of Use do not confer any third-party beneficiary rights.  All Sections of these Terms of Use shall survive the termination of these Terms of Use indefinitely. </p>
              <h2>N.  Territorial Restrictions </h2>

              <p>
                The information provided within the Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject Howlyr to any registration requirement within such jurisdiction or country. We reserve the right to limit the availability of the Service or any portion of the Service, to any person, geographic area, or jurisdiction, at any time and in our sole discretion, and to limit the quantities of any content, program, product, service or other feature that Howlyr provides. </p>
              <p>
                Software related to or made available by the Service may be subject to United States export controls. Thus, no software from the Service may be downloaded, exported or re-exported: (a) into (or to a national or resident of) any country to which the United States has embargoed goods; or (b) to anyone on the U.S. Treasury Department's list of Specially Designated Nationals or the U.S. Commerce Department's Table of Deny Orders. By downloading any software related to the Service, you represent and warrant that you are not located in, under the control of, or a national or resident of, any such country or on any such list. </p>
              <p>
                If you are a user or non-user who interacts with Howlyr and/or the Services outside the United States, you consent to having your personal data transferred to and processed in the United States. </p>

              <p>
                The effective date of these Terms of Use is November 5, 2018. These Terms of Use were written in English (US). To the extent any translated version of these Terms of Use conflicts with the English version, the English version controls.  Please contact us at <span><a href="mailto:support@howlyr.com"> support@howlyr.com</a></span> with any questions.
      </p>

            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  )
}

export default Terms;